package rot.pot.persistence.mybatis;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;
import rot.pot.entities.mybatis.Actor;
import rot.pot.entities.mybatis.Movie;

@Mapper
public interface ActorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACTOR
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    int deleteByPrimaryKey(Integer actorid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACTOR
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    int insert(Actor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACTOR
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    Actor selectByPrimaryKey(Integer actorid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACTOR
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    List<Actor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACTOR
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    int updateByPrimaryKey(Actor record);

    List<Movie> selectActorMovies(Integer actorId);

    int assignActorToMovie(@Param("actorid") Integer actorId, @Param("movieid") Integer movieId);
}