package rot.pot.persistence.mybatis;

import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;
import rot.pot.entities.mybatis.Actor;
import rot.pot.entities.mybatis.Movie;
import rot.pot.entities.mybatis.Rating;
import rot.pot.entities.mybatis.User;

import java.util.List;

@Mapper
public interface MovieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MOVIE
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    int deleteByPrimaryKey(Integer movieid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MOVIE
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    int insert(Movie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MOVIE
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    Movie selectByPrimaryKey(Integer movieid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MOVIE
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    List<Movie> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MOVIE
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    int updateByPrimaryKey(Movie record);

    List<Rating> selectRatings(@Param("movieid") Integer movieid);

    User selectUser(@Param("ratingid") Integer ratingid);

    List<Movie> selectMovie(@Param("movieid") Integer movieid);

    List<Actor> selectMovieActors(@Param("movieid") Integer movieid);
}