package rot.pot.persistence.mybatis;

import java.util.List;

import org.mybatis.cdi.Mapper;
import rot.pot.entities.mybatis.Rating;

@Mapper
public interface RatingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RATING
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    int deleteByPrimaryKey(Integer ratingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RATING
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    int insert(Rating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RATING
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    Rating selectByPrimaryKey(Integer ratingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RATING
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    List<Rating> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RATING
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    int updateByPrimaryKey(Rating record);
}