package rot.pot.entities.mybatis;

import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Movie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.MOVIEID
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    private Integer movieid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.NAME
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.RELEASEDATE
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    private Date releasedate;

    @Getter
    @Setter
    private List<Rating> ratings = new ArrayList<>();

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.MOVIEID
     *
     * @return the value of PUBLIC.MOVIE.MOVIEID
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public Integer getMovieid() {
        return movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.MOVIEID
     *
     * @param movieid the value for PUBLIC.MOVIE.MOVIEID
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public void setMovieid(Integer movieid) {
        this.movieid = movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.NAME
     *
     * @return the value of PUBLIC.MOVIE.NAME
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.NAME
     *
     * @param name the value for PUBLIC.MOVIE.NAME
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.RELEASEDATE
     *
     * @return the value of PUBLIC.MOVIE.RELEASEDATE
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public Date getReleasedate() {
        return releasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.RELEASEDATE
     *
     * @param releasedate the value for PUBLIC.MOVIE.RELEASEDATE
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public void setReleasedate(Date releasedate) {
        this.releasedate = releasedate;
    }
}