package rot.pot.entities.mybatis;

public class Rating {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RATING.RATINGID
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    private Integer ratingid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RATING.COMMENT
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RATING.RATING
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    private Integer rating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RATING.MOVIEID
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    private Integer movieid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RATING.USERID
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    private User user;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RATING.RATINGID
     *
     * @return the value of PUBLIC.RATING.RATINGID
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public Integer getRatingid() {
        return ratingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RATING.RATINGID
     *
     * @param ratingid the value for PUBLIC.RATING.RATINGID
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public void setRatingid(Integer ratingid) {
        this.ratingid = ratingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RATING.COMMENT
     *
     * @return the value of PUBLIC.RATING.COMMENT
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RATING.COMMENT
     *
     * @param comment the value for PUBLIC.RATING.COMMENT
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RATING.RATING
     *
     * @return the value of PUBLIC.RATING.RATING
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public Integer getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RATING.RATING
     *
     * @param rating the value for PUBLIC.RATING.RATING
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public void setRating(Integer rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RATING.MOVIEID
     *
     * @return the value of PUBLIC.RATING.MOVIEID
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public Integer getMovieid() {
        return movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RATING.MOVIEID
     *
     * @param movieid the value for PUBLIC.RATING.MOVIEID
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public void setMovieid(Integer movieid) {
        this.movieid = movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RATING.USERID
     *
     * @return the value of PUBLIC.RATING.USERID
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public User getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RATING.USERID
     *
     * @param userid the value for PUBLIC.RATING.USERID
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public void setUser(User user) {
        this.user = user;
    }
}