package rot.pot.entities.mybatis;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.USERID
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.DATEOFBIRTH
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    private Date dateofbirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.FIRSTNAME
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    private String firstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.LASTNAME
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.PASSWORD
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.USERNAME
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.USERID
     *
     * @return the value of PUBLIC.USER.USERID
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.USERID
     *
     * @param userid the value for PUBLIC.USER.USERID
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.DATEOFBIRTH
     *
     * @return the value of PUBLIC.USER.DATEOFBIRTH
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public Date getDateofbirth() {
        return dateofbirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.DATEOFBIRTH
     *
     * @param dateofbirth the value for PUBLIC.USER.DATEOFBIRTH
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public void setDateofbirth(Date dateofbirth) {
        this.dateofbirth = dateofbirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.FIRSTNAME
     *
     * @return the value of PUBLIC.USER.FIRSTNAME
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.FIRSTNAME
     *
     * @param firstname the value for PUBLIC.USER.FIRSTNAME
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.LASTNAME
     *
     * @return the value of PUBLIC.USER.LASTNAME
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.LASTNAME
     *
     * @param lastname the value for PUBLIC.USER.LASTNAME
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.PASSWORD
     *
     * @return the value of PUBLIC.USER.PASSWORD
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.PASSWORD
     *
     * @param password the value for PUBLIC.USER.PASSWORD
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.USERNAME
     *
     * @return the value of PUBLIC.USER.USERNAME
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.USERNAME
     *
     * @param username the value for PUBLIC.USER.USERNAME
     *
     * @mbg.generated Mon Apr 12 18:58:58 EEST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }
}